name: build
# Build the binaries and prepare a release

on:
  push:
    branches:
      - 'development'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout development
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: install
          ref: main

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'source/go.mod'

      - name: Prepare installation
        run: |
          find install -iname 'main-*' -delete;

      - name: Build
        run: |
          cd source
          for GOOS in linux windows; do
            export GOOS
            for GOARCH in arm64 amd64; do
              export GOARCH
              go build -ldflags="-s -w" -o "../install/main-${GOOS}-${GOARCH}-${{github.sha}}"
            done
          done
          sed -e "s|__VERSION__|${{github.sha}}|" invoke-binary.js.dist >../install/invoke-binary.js

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            install/main-linux-*
            install/main-windows-amd64-*
          args: -fq

      - name: Install
        run: |
          cd install
          for GOOS in linux windows; do
            for GOARCH in arm64 amd64; do
              git add "main-${GOOS}-${GOARCH}-${{github.sha}}"
            done
          done
          git add invoke-binary.js.dist
          git commit -m "Create binaries from ${{github.sha}}"

      - name: Create branch and Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          path: 'install'
          branch: 'build/build_${{github.sha}}'
          assignees: 'joernott'
          reviewers: 'joernott'
